"""create

Revision ID: 2a84d27cc03b
Revises: 
Create Date: 2021-04-03 14:20:19.258734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a84d27cc03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    customers = op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    rooms = op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    racks = op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(rooms,  [{"name":"Room1"},
                            {"name":"Room2"},
                            {"name":"Room3"},
                            {"name":"Room4"}  ])

    op.bulk_insert(customers,  [{"name":"Клиент-1"},
                                {"name":"Клиент-2"},
                                {"name":"Клиент-3"} ])

    op.bulk_insert(racks,  [{"name":"Rack1","size":42,"state":"occupied","customer":1,"room_id":1},
                                {"name":"Rack2","size":42,"state":"occupied","customer":2,"room_id":2},
                                {"name":"Rack3","size":21,"state":"free","customer":3,"room_id":3},
                                {"name":"Rack4","size":42,"state":"occupied","customer":1,"room_id":1},
                                {"name":"Rack5","size":42,"state":"free","customer":1,"room_id":1},
                                {"name":"Rack6","size":47,"state":"free","customer":2,"room_id":2},
                                {"name":"Rack7","size":42,"state":"occupied","customer":1,"room_id":1},
                                {"name":"Rack8","size":21,"state":"occupied","customer":1,"room_id":1} ])

    # ### end Alembic commands ###





def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack')
    op.drop_table('room')
    op.drop_table('customer')
    # ### end Alembic commands ###
